import 'package:backpack/features/assignment/assignment.dart';
import 'package:backpack/features/auth/auth.dart';
import 'package:backpack/features/course/course.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class FirebaseHelper {
  FirebaseHelper() {
    firestore = FirebaseFirestore.instance;
    users = firestore.collection('users');
    courses = firestore.collection('courses');
    assignments = firestore.collection('assignments');
  }
  late FirebaseFirestore firestore;
  late CollectionReference users;
  late CollectionReference courses;
  late CollectionReference assignments;

  // User Table Actions
  Future<Map<String, dynamic>> readUserData(String id) async {
    final snapshot = await users.doc(id).get();
    return snapshot.data() as Map<String, dynamic>;
  }

  Future insertUserData(UserData user) async {
    await users.doc(user.id).set(user.toDatabase());
  }

  Future updateUserData(UserData user) async {
    await users.doc(user.id).update(user.toDatabase());
  }

  Future deleteUserData(String id) async {
    await users.doc(id).delete();
  }

// TODO other actions
  Future<List<Course>> readCourses() async {
    final snapshot = await courses.get();
    final courseList = <Course>[];

    for (var item in snapshot.docs) {
      final course =
          Course.fromMap(item.data() as Map<String, dynamic>, item.id);
      courseList.add(course);
    }
    return courseList;
  }

  // Assignment Actions
  Future<List<Assignment>> readAssignments() async {
    final snapshot = await assignments.get();
    final assignmentList = <Assignment>[];

    for (var item in snapshot.docs) {
      final assignment =
          Assignment.fromMap(item.data() as Map<String, dynamic>, item.id);
      assignmentList.add(assignment);
    }
    return assignmentList;
  }

  // Returns the id generated by firebase
  Future insertAssignment(Assignment assignment) async {
    final newAssignmentId = assignments.doc();
    await newAssignmentId.set(assignment.toMap());
  }

  Future deleteAssignment(String assignmentId) async {
    await assignments.doc(assignmentId).delete();
  }
}
